import pygame.freetype

SCREEN_WIDTH = 300
SCREEN_HEIGHT = 300

FRAMES_PER_SECOND = 60
MILISECONDS_IN_SECOND = 1000
MILISECONDS_BETWEEN_FRAMES = MILISECONDS_IN_SECOND / FRAMES_PER_SECOND

INITIAL_AMOUNT_OF_GHOSTS = 7

GHOST_PLAYER_DETECTION_OFFSET = 20
GHOST_TIME_TO_MULTIPLY = 30
GHOST_RUNNING_AWAY_TIME = 2